<a href="https://colab.research.google.com/github/40423105/Machine-Learning-math/blob/main/vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#向量
a = np.array([-1,2])
b = np.array([3,1])

#加法
a_b = a + b
#乘法
a2 = a * 2
b3 = b * (-3)

print(a_b);print(a2);print(b3)

[2 3]
[-2  4]
[-9 -3]


In [ ]:
a = np.array([-2,2])
b = np.array([2,2])
#計算點積
ab_1 = np.inner(a,b)
#餘弦定理計算
#norm = |A| = (x1^2 + x2^2)^1/2
ab_2 = np.linalg.norm(a) * np.linalg.norm(b) * np.cos(np.pi/2)

print(ab_1);print(ab_2)

0
4.898587196589414e-16


In [ ]:
a = np.array([1,2,1])
b = np.array([1,-1,1])
#計算叉積
a_b = np.cross(a,b)

print(a_b)

[ 3  0 -3]


In [ ]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[2,2,0],[1,0,1],[0,1,1]])

det_a = np.linalg.det(a)
det_b = np.linalg.det(b)

print('a={0}\n D(a) = {1}'.format(a,np.round(det_a)))
print('b={0}\n D(b) = {1}'.format(b,np.round(det_b)))

a=[[1 2]
 [3 4]]
 D(a) = -2.0
b=[[2 2 0]
 [1 0 1]
 [0 1 1]]
 D(b) = -4.0


In [1]:
import numpy as np
a1 = np.random.random((4,3))
a2 = np.random.randint(1,11,(4,3))
a3 = np.ones((4,3))
a4 = np.zeros((4,3))
a5 = np.mat(np.arange(2,25,2)).reshape(4,3)
a6 = np.mat('1 2 3;4 5 6;7 8 9;10 11 12')
print('a1 = \n{}'.format(a1))
print('a2 = \n{}'.format(a2))
print('a3 = \n{}'.format(a3))
print('a4 = \n{}'.format(a4))
print('a5 = \n{}'.format(a5))
print('a6 = \n{}'.format(a6))

a1 = 
[[0.12565653 0.45333113 0.8600396 ]
 [0.13404155 0.2362723  0.09302177]
 [0.33775995 0.06663311 0.44536127]
 [0.60137377 0.02666237 0.55451224]]
a2 = 
[[6 8 8]
 [5 9 3]
 [2 9 8]
 [6 7 6]]
a3 = 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
a4 = 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
a5 = 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]
a6 = 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
